# COMP4471 Lab1: Introduction to Python & Numpy

#### What is Python?
- Python is a high-level, dyanmically typed multiparadigm programming language

#### Why do we learn Python?
- Simplicity: Pseudocode style
- Huge community: Libraries and Frameworks
- Most popular language when handling deep learning studies!

#### Now start your favorite python terminal!
- Anaconda is all you need: https://www.anaconda.com/products/individual
- Install Jupyter notebook: https://jupyter.org/install
- Pycharm, Spyder, VSCode,... Use your favorite!

## Python Basics
If you want a more intense tutorial, please refer to: https://notebooks.azure.com/Microsoft/projects/2018-Intro-Python/html/Introduction%20to%20Python.ipynb, or https://cs231n.github.io/python-numpy-tutorial/

The Zen of Python: https://www.python.org/dev/peps/pep-0020/

### Basic data types

In [1]:
a = 5 # int
print(type(a))

<class 'int'>


In [2]:
b = 7. # float
print(type(b))

<class 'float'>


In [3]:
a == b # Booleans: True, False

False

In [4]:
a != b

True

In [5]:
# strings
hw = 'hello' + ' world!'
hw

'hello world!'

In [6]:
# basic functions on strings
hw = hw.replace('!', '.')
hw

'hello world.'

In [7]:
hw = hw.split()
hw

['hello', 'world.']

## Python Containers

### Lists: The Python equivalent fo anarray

In [8]:
x = [1, 2, 3]

In [9]:
x

[1, 2, 3]

In [10]:
# list can contain different types of elements
x[0] = 'hello'
x

['hello', 2, 3]

In [11]:
# basic functions
x.append(4.0)
x

['hello', 2, 3, 4.0]

In [12]:
# loops
for element in x:
    print(element)

hello
2
3
4.0


### Dictionaries: (key, value) pair

In [13]:
d = {'cat': 'cute', 'dog': 'furry'}

In [14]:
d

{'cat': 'cute', 'dog': 'furry'}

In [15]:
# get value
d['cat']

'cute'

In [16]:
# set an entry
d['fish'] = 'wet'
d

{'cat': 'cute', 'dog': 'furry', 'fish': 'wet'}

In [17]:
# loops
for key, value in d.items():
    print('A %s is %s.'%(key, value))

A cat is cute.
A dog is furry.
A fish is wet.


### Sets: An unordered collection of distinct elements

In [18]:
animals = {'cat', 'dog'}
animals

{'cat', 'dog'}

In [19]:
# add/remove elements to set
animals.add('bear')
animals

{'bear', 'cat', 'dog'}

In [20]:
animals.remove('cat')
animals

{'bear', 'dog'}

### Tuple: An (immutable) ordered list of values

In [21]:
d = {(x, x + 1): x for x in range(10)}
d

{(0, 1): 0,
 (1, 2): 1,
 (2, 3): 2,
 (3, 4): 3,
 (4, 5): 4,
 (5, 6): 5,
 (6, 7): 6,
 (7, 8): 7,
 (8, 9): 8,
 (9, 10): 9}

## Python Functions

In [22]:
# define
def sign(x):
    if x > 0:
        return 'positive'
    elif x < 0:
        return 'negative'
    else:
        return 'zero'

In [23]:
# call
for x in [-1, 0, 1]:
    print(sign(x))

negative
zero
positive


In [24]:
# set default augument
def hello(name, loud=False):
    if loud:
        print('HELLO, %s!'%name.upper())
    else:
        print('hello, %s'%name)

In [25]:
hello('alice')

hello, alice


In [26]:
hello('alice', loud=True)

HELLO, ALICE!


## Python Classes

In [27]:
# define
class Greeter(object):
    # constructor
    def __init__(self, name):
        self.name = name
    # instance method
    def hello(self, loud=False):
        if loud:
            print('HELLO, %s!'%self.name.upper())
        else:
            print('hello, %s'%self.name)

In [28]:
g = Greeter('Bob')

In [29]:
g # g is an instance of the Greeter class

In [30]:
g.name

'Bob'

In [31]:
g.hello()

hello, Bob


In [32]:
g.hello(loud=True)

HELLO, BOB!


# Numpy

#### What is Numpy?
- A scientific computing library for Python
- Linear algebra, Fourier transform, random number generation...

#### Why do we learn Numpy?
- N-dimensional array (tensor) manipulation
- You'll use in your assignments to implement neural networks & other functions with Numpy!

#### How to install numpy?
- simply with ``conda install numpy`` on your terminal (or, ``pip install numpy``)
- if you are in trouble, refer to: https://numpy.org/install/.

## Numpy Basics

In [33]:
# importing
import numpy as np

In [34]:
# tensor (array) creation
a = np.array([1, 2, 3])
a

array([1, 2, 3])

In [35]:
# shape: size of the tensor
a.shape

(3,)

In [36]:
b = np.array([[1, 2, 3], [1, 2, 3]])
b

array([[1, 2, 3],
       [1, 2, 3]])

In [37]:
b.shape

(2, 3)

In [38]:
np.ndim(b)  # same as rank (number of total dimension)

2

In [39]:
c = np.array([[1, 2, 3], [2, 3, 4]])
c

array([[1, 2, 3],
       [2, 3, 4]])

In [40]:
c.shape, np.ndim(c)

((2, 3), 2)

In [41]:
# specify data type
print(c.dtype)
d = np.array([[1, 2, 3], [2, 3, 4]], dtype=np.int32)
print(d.dtype)

int64
int32


## Tensor Creation

### Useful Functions

In [42]:
# np.zeros()
# Return a new array of given shape and type, filled with zeros.
a = np.zeros((2, 3))
a

array([[0., 0., 0.],
       [0., 0., 0.]])

In [43]:
# np.ones()
# Return a new array of given shape and type, filled with ones.
a = np.ones((2, 3))
a

array([[1., 1., 1.],
       [1., 1., 1.]])

In [44]:
# np.full(shape, fill_value, dtype=None, order='C')
# Return a new array of given shape and type, filled with fill_value.
a = np.full((2, 3), 10)
a

array([[10, 10, 10],
       [10, 10, 10]])

In [45]:
# np.eye(N, M=None, k=0, dtype=<class 'float'>, order='C')
# Return a 2-D array with ones on the diagonal and zeros elsewhere.
a = np.eye(5)
a

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [46]:
# np.random.rand()
# Random values in a given shape.
a = np.random.rand(2, 3)
a

array([[0.8340953 , 0.6735379 , 0.20859473],
       [0.1288441 , 0.71905766, 0.37641312]])

## Tensor Indexing
Note that index starts at 0 in Python!

In [47]:
a = np.array([1, 2, 3])
# use []
print(a[0], a[1], a[2])

1 2 3


In [48]:
b = np.array([[1, 2, 3], [4, 5, 6]])
print(b[0]) # -> [1, 2, 3]
print(b[0,0]) # -> 1

[1 2 3]
1


In [49]:
# fetching a sub-array of the n-D array
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(a[:2, 1:3])

[[2 3]
 [6 7]]


In [50]:
b = a[:2, 1:3]
b

array([[2, 3],
       [6, 7]])

In [51]:
# slicing does not copy arrays
print(b[0, 0], a[0, 1])
b[0, 0] = 100
print(b[0, 0], a[0, 1])  # a[0, 1] is also changed!

2 2
100 100


In [52]:
# integer indexing
# if you want to index many elements:
print(np.array([a[0, 0], a[1, 1], a[2, 0], a[2, 3]]))
# you can write as:
print(a[[0, 1, 2, 2], [0, 1, 0, 3]])

[ 1  6  9 12]
[ 1  6  9 12]


In [53]:
# boolean indexing
# select elements that satisfy certain conditions
a = np.array([[1, 2], [3, 4], [5, 6]])
bool_idx = (a > 2)
print(a[bool_idx])
# same as using np.where as:
print(a[np.where(a > 2)])

[3 4 5 6]
[3 4 5 6]


In [54]:
# np.where is useful function
# Return elements chosen from x or y depending on condition.
print(a)
print(np.where(a > 2, a**2, 100)) # if elements x in a satisfies x > 2 replaced by a**2, else by 100

[[1 2]
 [3 4]
 [5 6]]
[[100 100]
 [  9  16]
 [ 25  36]]


In [55]:
# more complicated conditions are also applicable
bool_idx = (np.sqrt(a) > 2)
print(a[bool_idx])
# same as using np.where as:
print(a[np.where(np.sqrt(a) > 2)])

[5 6]
[5 6]


## Tensor Arithmetic

In [56]:
# assume x and y have the same shape:
x = np.array([[1, 2], [3, 4], [5, 6]])
y = np.array([[3, 4], [5, 6], [7, 8]])

In [57]:
print(x + y)

[[ 4  6]
 [ 8 10]
 [12 14]]


In [58]:
print(x - y)

[[-2 -2]
 [-2 -2]
 [-2 -2]]


In [59]:
print(x * y)

[[ 3  8]
 [15 24]
 [35 48]]


In [60]:
print(x / y)

[[0.33333333 0.5       ]
 [0.6        0.66666667]
 [0.71428571 0.75      ]]


In [61]:
print(np.sqrt(x))

[[1.         1.41421356]
 [1.73205081 2.        ]
 [2.23606798 2.44948974]]


In [62]:
# transpose
print(x)
print(x.T)

[[1 2]
 [3 4]
 [5 6]]
[[1 3 5]
 [2 4 6]]


In [63]:
# dot product
print(np.dot(x, y.T))
# or,
print(x.dot(y.T))

[[11 17 23]
 [25 39 53]
 [39 61 83]]
[[11 17 23]
 [25 39 53]
 [39 61 83]]


## Broadcasting
- "Broadcasting describes how numpy treats arrays with different shapes during arithmetic operations. Subject to certain constraints, the smaller array is “broadcast” across the larger array so that they have compatible shapes."
- Official document: https://numpy.org/doc/stable/user/basics.broadcasting.html

In [64]:
a = np.array([[1, 2, 3], [4, 5, 6]])
a + 100  # 100 is automatically broadcasted into np.array([[100, 100, 100], [100, 100, 100]])

array([[101, 102, 103],
       [104, 105, 106]])

In [65]:
mean = np.mean(a, axis=0)
mean

array([2.5, 3.5, 4.5])

In [66]:
a - mean # (2,3) - (3) -> mean in broadcasted into np.array(mean, mean)

array([[-1.5, -1.5, -1.5],
       [ 1.5,  1.5,  1.5]])

In [67]:
# Only two cases are allowed for each dimension:
# - they have the same size
# - one of the size is 1
a = np.random.randint(10, size=(2, 3, 4))
b = np.random.randint(10, size=(3, 4))
c = np.random.randint(10, size=(4))
d = np.random.randint(10, size=(2, 4))

In [68]:
a

array([[[1, 9, 1, 4],
        [6, 6, 9, 0],
        [1, 6, 7, 5]],

       [[6, 9, 2, 6],
        [1, 1, 8, 0],
        [7, 0, 8, 1]]])

In [69]:
b # can be viewed (1, 3, 4)

array([[8, 6, 9, 0],
       [4, 4, 1, 6],
       [8, 8, 9, 7]])

In [70]:
c

array([5, 5, 3, 9])

In [71]:
d

array([[8, 1, 8, 2],
       [6, 2, 1, 6]])

In [72]:
a + b

array([[[ 9, 15, 10,  4],
        [10, 10, 10,  6],
        [ 9, 14, 16, 12]],

       [[14, 15, 11,  6],
        [ 5,  5,  9,  6],
        [15,  8, 17,  8]]])

In [73]:
a + c

array([[[ 6, 14,  4, 13],
        [11, 11, 12,  9],
        [ 6, 11, 10, 14]],

       [[11, 14,  5, 15],
        [ 6,  6, 11,  9],
        [12,  5, 11, 10]]])

In [74]:
b + c

array([[13, 11, 12,  9],
       [ 9,  9,  4, 15],
       [13, 13, 12, 16]])

In [75]:
a + d  # does not meet the conditions!

ValueError: operands could not be broadcast together with shapes (2,3,4) (2,4) 

In [76]:
b + d # does not meet the conditions!

ValueError: operands could not be broadcast together with shapes (3,4) (2,4) 

## Other libraries you may have to use:
### Scipy
- fundamental library for scientific computing including image manipulation etc.

### Matplotlib
- library for plotting

## Remember: 
- Index starts from 0 not 1
- Deep vs shallow (assignment) copy
- Avoid loops use broadcast and list comprehensions
- Add comments
- Meaningful naming convention
- Always check data type, python is  forgiving so you might get fooled
- Check package compatibility
- When in doubt, use conda not pip
- Documentations are your best friend

### AND, Google before ask somebody else!!